from __future__ import annotations

import re

from text_to_ansys.builders.base import APDLBuildResult, BaseAPDLBuilder
from text_to_ansys.schema import BoundaryConditionSpec, LoadSpec, SimulationSpec, TargetSpec


class StaticStructuralBuilder(BaseAPDLBuilder):
    analysis_type = "static_structural"

    def build(self, spec: SimulationSpec) -> APDLBuildResult:
        if not self.supports(spec):
            raise ValueError(f"unsupported analysis type: {spec.analysis_type}")

        lines: list[str] = []
        lines.extend(self._header(spec))
        lines.extend(self._prep7(spec))
        lines.extend(self._boundary_conditions(spec))
        lines.extend(self._loads(spec))
        lines.extend(self._solution())
        lines.extend(self._post(spec))

        script = "\n".join(lines).rstrip() + "\n"
        return APDLBuildResult(
            script=script,
            warnings=[],
            required_outputs=list(spec.outputs),
            metadata={"analysis_type": spec.analysis_type, "builder": self.__class__.__name__},
        )

    def _header(self, spec: SimulationSpec) -> list[str]:
        safe_title = spec.title.replace("\n", " ").replace("\r", " ")
        return [
            "/CLEAR,NOSTART",
            f"/TITLE,{safe_title}",
            "! Generated by text-to-ansys",
            f"! Unit system: {spec.unit_system}",
            "FINISH",
            "",
        ]

    def _prep7(self, spec: SimulationSpec) -> list[str]:
        params = spec.geometry.parameters
        material = spec.primary_material
        lines = [
            "/PREP7",
            "! Element type",
            f"ET,1,{spec.element.type}",
            "TYPE,1",
            f"MAT,{spec.element.material_id}",
            "",
            "! Material: linear isotropic",
            f"MP,EX,{material.id},{self._num(material.youngs_modulus)}",
            f"MP,PRXY,{material.id},{self._num(material.poisson_ratio)}",
        ]
        if material.density is not None:
            lines.append(f"MP,DENS,{material.id},{self._num(material.density)}")

        lines.extend(
            [
                "",
                "! Geometry: block/cantilever beam",
                (
                    "BLOCK,"
                    f"0,{self._num(params['length'])},"
                    f"0,{self._num(params['width'])},"
                    f"0,{self._num(params['height'])}"
                ),
                "",
                "! Mesh",
                f"ESIZE,{self._num(spec.mesh.global_size)}",
                "VMESH,ALL",
                "ALLSEL,ALL",
                "",
            ]
        )
        return lines

    def _boundary_conditions(self, spec: SimulationSpec) -> list[str]:
        lines = ["! Boundary conditions"]
        for index, bc in enumerate(spec.boundary_conditions, start=1):
            lines.append(f"! BC {index}: {bc.kind}")
            lines.extend(self._select_target(bc.target, spec))
            lines.extend(self._apply_bc(bc))
            lines.append("ALLSEL,ALL")
            lines.append("")
        return lines

    def _loads(self, spec: SimulationSpec) -> list[str]:
        lines = ["! Loads"]
        for index, load in enumerate(spec.loads, start=1):
            lines.append(f"! Load {index}: {load.kind}")
            lines.extend(self._select_target(load.target, spec))
            lines.extend(self._apply_load(load, index))
            lines.append("ALLSEL,ALL")
            lines.append("")
        return lines

    def _solution(self) -> list[str]:
        return [
            "FINISH",
            "/SOLU",
            "ANTYPE,STATIC",
            "SOLVE",
            "FINISH",
            "",
        ]

    def _post(self, spec: SimulationSpec) -> list[str]:
        lines = [
            "/POST1",
            "SET,LAST",
            "! Basic result listings for log review",
        ]
        if "max_total_displacement" in spec.outputs or "max_directional_displacement" in spec.outputs:
            lines.append("PRNSOL,U,COMP")
        if "max_von_mises_stress" in spec.outputs:
            lines.append("PRNSOL,S,PRIN")
        lines.extend(["FINISH", ""])
        return lines

    def _apply_bc(self, bc: BoundaryConditionSpec) -> list[str]:
        return [f"D,ALL,{dof},{self._num(bc.value)}" for dof in bc.dofs]

    def _apply_load(self, load: LoadSpec, index: int) -> list[str]:
        if load.kind == "pressure":
            return [f"SF,ALL,PRES,{self._num(load.value)}"]
        if load.direction is None:
            raise ValueError("force load requires direction")
        node_count = f"NCOUNT{index}"
        force_each = f"FEACH{index}"
        return [
            f"*GET,{node_count},NODE,0,COUNT",
            f"*IF,{node_count},LE,0,THEN",
            f"  /COM,WARNING: load {index} target selected no nodes",
            "*ELSE",
            f"  {force_each}={self._num(load.value)}/{node_count}",
            f"  F,ALL,F{load.direction},{force_each}",
            "*ENDIF",
        ]

    def _select_target(self, target: TargetSpec, spec: SimulationSpec) -> list[str]:
        if target.selector == "nodes":
            return [f"CMSEL,S,{target.expression}"]
        axis, value = self._parse_location_expression(target.expression, spec)
        return [
            "ALLSEL,ALL",
            f"NSEL,S,LOC,{axis},{self._num(value)}",
        ]

    def _parse_location_expression(self, expression: str, spec: SimulationSpec) -> tuple[str, float]:
        match = re.fullmatch(r"\s*([xyzXYZ])\s*=\s*([A-Za-z_][A-Za-z0-9_]*|[-+]?\d*\.?\d+(?:[eE][-+]?\d+)?)\s*", expression)
        if not match:
            raise ValueError(f"unsupported target expression: {expression!r}")

        axis = match.group(1).upper()
        raw_value = match.group(2)
        value_map = {
            "length": spec.geometry.parameters["length"],
            "width": spec.geometry.parameters["width"],
            "height": spec.geometry.parameters["height"],
        }
        if raw_value in value_map:
            return axis, value_map[raw_value]
        try:
            return axis, float(raw_value)
        except ValueError as exc:
            raise ValueError(f"unknown target expression value: {raw_value!r}") from exc

    def _num(self, value: float) -> str:
        return f"{value:.12g}"

